"""Pure builders for Cat-VRS, synthetic patient, and answer-key records."""

from __future__ import annotations

import copy
import hashlib
from typing import Any

from .validation import validate_candidate, validate_catvar


def _stable_id(prefix: str, *parts: object) -> str:
    payload = "\x1f".join(str(part) for part in parts).encode("utf-8")
    return f"{prefix}:{hashlib.sha256(payload).hexdigest()[:20]}"


def build_catvar(candidate: dict[str, Any]) -> dict[str, Any]:
    """Wrap a supplied VRS Allele; never normalize or calculate a GA4GH digest."""

    validate_candidate(candidate)
    category = candidate["category"]
    category_id = category["id"]

    catvar: dict[str, Any] = {
        "id": category_id,
        "type": "CategoricalVariant",
        "name": category["name"],
        "description": category.get(
            "description", "Canonical allele category generated by the pilot pipeline."
        ),
        "constraints": [
            {
                "type": "DefiningAlleleConstraint",
                "allele": copy.deepcopy(candidate["defining_allele"]),
            }
        ],
    }

    aliases = category.get("aliases")
    if aliases:
        catvar["aliases"] = list(dict.fromkeys(aliases))

    if category_id.startswith("clingen:CA"):
        caid = category_id.removeprefix("clingen:")
        catvar["mappings"] = [
            {
                "coding": {
                    "system": "https://reg.clinicalgenome.org/",
                    "code": caid,
                    "iris": [
                        "https://reg.clinicalgenome.org/redmine/projects/registry/"
                        f"genboree_registry/by_caid?caid={caid}"
                    ],
                },
                "relation": "exactMatch",
            }
        ]

    # Members are intentionally absent. A CAID may identify the category without
    # requiring us to infer additional congruent allele representations.
    validate_catvar(catvar)
    return catvar


def build_records(
    candidate: dict[str, Any], seed: int
) -> tuple[dict[str, Any], dict[str, Any]]:
    """Create a patient record and separately keyed gold annotations."""

    catvar = build_catvar(candidate)
    source = candidate["source"]
    patient_id = _stable_id("synthetic-patient", seed, source["record_id"])
    observation_id = _stable_id("synthetic-observation", patient_id, catvar["id"])

    patient = {
        "schemaVersion": "0.1.0",
        "id": patient_id,
        "type": "SyntheticPatientRecord",
        "synthetic": True,
        "observations": [
            {
                "id": observation_id,
                "type": "VariantObservation",
                "categoricalVariant": catvar,
            }
        ],
        "provenance": {
            "source": source["name"],
            "sourceRecordId": source["record_id"],
            "sourceRelease": source["release"],
        },
    }

    answer_key = {
        "schemaVersion": "0.1.0",
        "type": "SyntheticPatientAnswerKey",
        "patientId": patient_id,
        "answers": [
            {
                "observationId": observation_id,
                "sourceAnnotations": copy.deepcopy(
                    candidate.get("gold_annotations", [])
                ),
            }
        ],
        "provenance": copy.deepcopy(source),
    }
    return patient, answer_key
